
#General settings
[general]
	#The CurseForge project ID for the modpack
	#Range: > 0
	modpackProjectID = 1183647
	#The name of the modpack
	modpackName = "Create: Burgified"
	#The version of the modpack
	modpackVersion = "0.8.1"
	#Use the metadata.json to determine the modpack version
	#ONLY ENABLE THIS IF YOU KNOW WHAT YOU ARE DOING
	useMetadata = false

